// Authentication Action Type
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

// Route Action Type
export const ROUTE_HOME = 'ROUTE_HOME';
export const ROUTE_ME = 'ROUTE_ME';
export const ROUTE_DETAIL = 'ROUTE_DETAIL';
export const ROUTE_SET_SIDEBAR = 'ROUTE_SET_SIDEBAR';
export const ROUTE_OPEN_COMMENT = 'ROUTE_OPEN_COMMENT';
export const ROUTE_CLOSE_COMMENT = 'ROUTE_CLOSE_COMMENT';

// Toast Action Type
export const TOAST_SHOW = 'TOAST_SWOW';
export const TOAST_HIDE = 'TOAST_HIDE';

// Post Action Type
export const POST_REQUEST = 'POST_REQUEST';
export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_FAILURE = 'POST_FAILURE';
export const POST_DETAIL_REQUEST = 'POST_DETAIL_REQUEST';
export const POST_DETAIL_SUCCESS = 'POST_DETAIL_SUCCESS';
export const POST_DETAIL_FAILURE = 'POST_DETAIL_FAILURE';
export const POST_ADD_COMMENT = 'POST_ADD_COMMENT';
export const POST_SET_LIKE = 'POST_SET_LIKE';
export const POST_SET_GOING = 'POST_SET_GOING';
export const POST_CLEAR = 'POST_CLEAR';

// Filter Action Type
export const SEARCH_DATE = 'SEARCH_DATE';
export const SEARCH_CHANNEL = 'SEARCH_CHANNEL';
export const SEARCH_CHANNEL_LIST = 'SEARCH_CHANNEL_LIST';
export const SEARCH_OPEN_DATE_PICKER = 'SEARCH_OPEN_DATE_PICKER';
export const SEARCH_CLOSE_DATE_PICKER = 'SEARCH_CLOSE_DATE_PICKER';
export const SEARCH_ON_SELECT_DATE_PICKER = 'SEARCH_ON_SELECT_DATE_PICKER';
export const SEARCH_SUBMIT = 'SEARCH_SUBMIT';
export const SEARCH_CLEAR = 'SEARCH_CLEAR';
